### ISSUE TITLE
🔍️ Google Snippet

### ISSUE THREAD

**Issue by LouiFi** [Popoyoko/les-ecuries#60]
Actual :
![image](https://user-images.githubusercontent.com/24565656/214007376-e1b40aed-558f-4117-b006-4fb0db42c63d.png)

Need :
![image](https://user-images.githubusercontent.com/24565656/214007294-56427fe0-c87a-4da3-9a92-0982ede87fbe.png)

**Comment by Emerson452** [comment]
resolved by this [pr](https://github.com/Popoyoko/les-ecuries/pull/62)

**Comment by Emerson452** [comment]
![image](https://user-images.githubusercontent.com/93705484/214065061-8dc5117f-0e36-4266-9b07-54c77bc83456.png)

**Comment by LouiFi** [comment]
:clap:
